name: CI Frontend

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        workdir: [manning-patrol-android-frontend, manning-patrol-desktop-frontend]
        node-version: [20.x, 22.x]

    defaults:
      run:
        working-directory: ${{ matrix.workdir }}

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ${{matrix.workdir}}/package-lock.json
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test --if-present
