name: CodeScene

on:
  ["push", "pull_request"]

jobs:
  code-health:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Install CodeScene CLI
        run: curl https://downloads.codescene.io/enterprise/cli/install-cs-tool-sh | sh 

      - name: Run delta analysis
        env:
          CS_ACCESS_TOKEN: ${{secrets.CS_ACCESS_TOKEN}}
        run: cs delta --git-hook
