name: Main Workflow
run-name: ${{ github.actor }} is running workflows
on: [push, pull_request]
jobs:
  frontend:
   uses: .github/workflows/github-actions-fe.yml
  backend:
    uses: .github/workflows/github-actions-be.yml